- include: playbooks/util-install-ohmyzsh.yml

- include: playbooks/step1-install-docker.yml

- include: playbooks/step2-install-ddc.yml

- include: playbooks/step3-deploy-registry.yml

- include: playbooks/op-ucp-backup.yml