---

#docker_cs_yum_repo: "https://packages.docker.com/{{ docker_csengine_version }}/yum/repo/main/centos/7"
docker_cs_yum_repo:  https://yum.dockerproject.org/repo/main/centos/7/
docker_py_package: docker-py