---

- name: Install yum-utils if necessary.
  yum:
    name: yum-utils
    state: present


# - name: Add the YUM Docker repository.
#   yum_repository:
#     description: Docker repository.
#     name: docker
#     baseurl: "{{ docker_cs_yum_repo }}"
    #gpgcheck: yes
    #enabled: yes
    #gpgkey: "{{ docker_cs_pubkey }}" 

- name: Add the YUM Docker repository
  shell: yum-config-manager --add-repo https://docs.docker.com/engine/installation/linux/repo_files/centos/docker.repo


- name: update yum cache index
  shell: yum makecache fast
  

- name: Install Docker Engine.
  package:
    name: docker-engine
    state: present

  
- name: Enable the Docker daemon as a service and start it.
  service:
    name: docker.service
    state: started
    enabled: yes
    

- name: Create servide dropin directroy
  file: 
    path: /etc/systemd/system/docker.service.d
    state: directory


- name: Apply http_proxy to docker 
  template:
    src: http.conf.in  
    dest: /etc/systemd/system/docker.service.d/http.conf


- name: Reload systemd and restat docker service
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
  changed_when: false