---

- name: Import Docker RPM public key for CS packages.
  rpm_key:
    key: "{{ docker_cs_pubkey }}"
    state: present
  when: is_csengine

- name: Install yum-utils if necessary.
  yum:
    name: yum-utils
    state: present


# - name: Add the YUM Docker repository.
#   yum_repository:
#     description: Docker Repository.
#     name: docker
#     baseurl: "{{ docker_yum_repo }}"
#     enabled: yes

- name: Add the YUM Docker repository
  shell: yum-config-manager --add-repo {{ docker_yum_repo }}

- name: update yum cache index
  shell: yum makecache fast
  

- name: Install Docker CS Engine.
  package:
    name: "{{ docker_package_name }}"
    state: present

  
- name: Enable the Docker daemon as a service and start it.
  service:
    name: docker.service
    state: started
    enabled: yes
    

- name: Create servide dropin directroy
  file: 
    path: /etc/systemd/system/docker.service.d
    state: directory
  when: http_proxy is defined


- name: Apply http_proxy to docker 
  template:
    src: http.conf.in  
    dest: /etc/systemd/system/docker.service.d/http.conf
  notify: Reload systemd
  when: http_proxy is defined

- name: Get docker restarted
  command: /bin/true
  notify: Restart docker 

# from ansible version 2.2
# - name: Reload systemd and restat docker service
#   systemd:
#     state: restarted
#     daemon_reload: yes
#     name: docker
#   changed_when: false