
---
- name: Reload systemd
  command: systemctl --system daemon-reload


- name: Restart docker 
  command: /bin/true
  notify: 
    - stop docker 
    - start docker 


- name: Stop docker 
  service: name=docker state=stopped
    

- name: Start docker 
  service: name=docker state=started

...

