
- name: Get the certificates used by UCP 
  get_url: 
    url:  https://"{{ docker_ucp_host_address }}"/ca 
    dest: /tmp/ucp-ca.pem
  delegate_to: "{{ item }}"
  run_once: yes


- name: install DTR 
  shell: docker run -it --rm 
          docker/dtr install
          --ucp-url {{ groups['docker_ucp_node'][0]  }} 
          --ucp-node {{ hostvars[groups['docker_ucp_node'][0]].ansible_hostname }}
          --dtr-external-url {{ groups['docker_ucp_node'][0] }}
          --ucp-username {{ docker_ucp_admin_username }}
          --ucp-password {{ docker_ucp_admin_password }} 
          --ucp-ca ${cat /tmp/ucp-ca.pem}
  delegate_to: "{{ item }}"
  run_once: yes
