---

- name: Import Docker RPM public key for CS packages.
  rpm_key:
    key: "{{ docker_cs_pubkey }}"
    state: present

- name: Install yum-utils if necessary.
  yum:
    name: yum-utils
    state: present

- name: Add the YUM Docker repository.
  yum_repository:
    name: docker
    description: Docker CS repository.
    baseurl: "{{ docker_cs_yum_repo }}"


- name: Install Docker CS Engine.
  package:
    name: docker-engine
    state: present

- name: Enable the Docker daemon as a service and start it.
  service:
    name: docker.service
    state: started
    enabled: yes

